FROM microsoft/dotnet:2.0.0-sdk-2.0.2

ARG buildVersion
ARG uri
ARG authKey
ARG consistencyLevel="1.0.0"

ENV BuildVersion=${buildVersion}
ENV Uri=${uri}
ENV AuthKey=${authKey}
ENV ConsistencyLevel=${consistencyLevel}

ADD build workDir/build
ADD src workDir/src

WORKDIR workDir/build

RUN ["powershell", ".\\simplebuild.ps1"]